## This pair of functions allows the inverse of a matrix to be cached for later use.
## Function 1: makeCacheMatrix(A) generates a special type of matrix that allows for 
## cachingof the inverse.
## Function 2: cacheSolve(A,... ) returns the inverse of a matrix, retrieving a previously
## cached value if available.



## makeCacheMatrix(A) takes as input a matrix A and outputs a "special" matrix with
## additional properties. Specifically, this "special" matrix is a list of functions:
# A$get          - returns the current value of the matrix
# A$set(X)       - overwrites the current value of the matrix with that given by X.
# A$getinv()     - retrieves the matrix inverse associated with the matrix 
#                  (will return NULL if it has not yet been caluclated)
# A$setinv(Inv)  - stores the matrix inverse value given by Inv.

makeCacheMatrix <- function(A = matrix()) {
  # Initialize inverse to NULL value
  Ainv <- NULL
  
  # Define "set" function, which sets the matrix to B
  set <- function(B) {
    A <<- B
    Ainv <<- NULL}
  
  # Define the "get" function, which returns the matrix
  get <- function() A
  
  # Define the "setinv" function, which sets the matrix inverse value (Ainv) to Inv
  setinv <- function(Inv) Ainv <<- Inv
  
  # Define the "getinv" function, which returns the matrix inverse, Ainv (could be NULL)
  getinv <- function() Ainv
  
  # Return list of set, get, setinv, and getinv functions
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## cacheSolve(A, ...) takes as input a matrix A (generated by makeCacheMatrix above) and returns
## its inverse. The function first checks if the inverse of the matrix has already been
## computed. If it has, it returns the stored inverse. If it hasn't, the function computes,
## stores, and returns the inverse.

cacheSolve <- function(A, ...) {
  # Retrieve the inverse associated with A using the function "getinv"
  Ainv <- A$getinv()
  
  # If the inverse value is present (i.e. not NULL), return the inverse value.
  if(!is.null(Ainv)) {
    message("getting cached data")
    return(Ainv)}
  
  # Otherwise, retrieve the matrix value using the "get" function.
  data <- A$get()
  
  # Calculate the matrix inverse (using the base R function "solve")
  Ainv <- solve(data, ...)
  
  # Associate the inverse value with the "special" matrix using the "setinv" function.
  A$setinv(Ainv)
  
  # Return the newly calculated inverse value.
  return(Ainv)
}
